subgraphs:
  covies:
    routing_url: http://localhost:3000/graphql
    schema:
      subgraph_url: http://localhost:3000/graphql
  coeather:
    routing_url: http://localhost:3001/graphql
    schema:
      subgraph_url: http://localhost:3001/graphql
